name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 2

      - name: Execute Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo fuser -k 8080/tcp || true
            cd /home/ubuntu/app
            
            APP_NAME=$(ls | grep '.jar' | grep -vE 'plain|stubs' | head -n 1)
            
            if [ -z "$APP_NAME" ]; then
              echo "Error: No executable JAR file found!"
              exit 1
            fi

            nohup java -jar \
              -Dspring.profiles.active=prod \
              -Dspring.jpa.hibernate.ddl-auto=update \
              -DRDS_HOSTNAME=${{ secrets.RDS_HOSTNAME }} \
              -DRDS_USERNAME=${{ secrets.RDS_USERNAME }} \
              -DRDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              -DNAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
              -DNAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
              -DJWT_SECRET=${{ secrets.JWT_SECRET }} \
              -DEC2_HOST=${{ secrets.EC2_HOST }} \
              $APP_NAME > nohup.out 2>&1 &
